name: gift-list

services:
  giftlist:
    build: .
    container_name: gift-list
    image: gift-list:latest
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./.env
        target: /home/gift-list/app/.env
        read_only: true
      - type: bind
        source: /var/log/gift-list
        target: /var/log/gift-list
        read_only: false

  migrations:
    build:
      target: migrations
      context: .
    container_name: gift-list-migrations
    image: gift-list-migrations:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - path: .env
        required: true
    volumes:
      - type: bind
        source: ./.env
        target: /home/gift-list/app/.env
        read_only: true
