openapi: 3.0.0

info:
  title: gift-list
  version: 1.0.0

paths:

  /groups:
    get:
      summary: Lists all the groups
      tags:
        - Groups
      security:
        - adminAuth: []
      responses:
        '200':
          description: The list of the groups
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Group'
    post:
      summary: Create a new group
      tags:
        - Groups
      security:
        - adminAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateGroup'
      responses:
        '201':
          description: The created group.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
        '500':
          description: Some server error

  /groups/{name}:
    get:
      summary: Get the group by name
      tags:
        - Groups
      security:
        - adminAuth: []
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: The group name
      responses:
        '200':
          description: The group
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
        '404':
          description: The group was not found
    put:
      summary: Update the group by the id
      tags:
        - Groups
      security:
        - adminAuth: []
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: The group name
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateGroup'
      responses:
        '204':
          description: The group was updated
        '404':
          description: The group was not found
        '500':
          description: Some error happened
    delete:
      summary: Remove the group by name
      tags:
        - Groups
      security:
        - adminAuth: []
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: The book name
      responses:
        '204':
          description: The group was deleted
        '404':
          description: The group was not found

components:

  securitySchemes:
    adminAuth:
      type: http
      scheme: basic

  schemas:

    Group:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: The group name
      example:
        name: Jedi order

    CreateGroup:
      type: object
      required:
        - name
        - password
      properties:
        name:
          type: string
          description: The group name
        password:
          type: string
          description: The group password
      example:
        name: Jedi order
        password: maythe4bewithyou

    UpdateGroup:
      type: object
      required:
        - password
      properties:
        password:
          type: string
          description: The group password
      example:
        password: maythe4bewithyou

tags:
  - name: Groups
    description: The groups
